### ISSUE TITLE
Daily Log 2021-04-08

### ISSUE THREAD

**Issue by dongsubkim** [dongsubkim/dailylog#16]
# Daily Log 2021-04-08

## TODO

 - [x] [leetcode](https://leetcode.com/explore/challenge/card/april-leetcoding-challenge-2021/594/week-2-april-8th-april-14th/3701/)
 - [x] [project euler](https://projecteuler.net/problem=26)
 - [x] [programmers](https://programmers.co.kr/learn/courses/30/lessons/68644)
 - [x] [programmers](https://programmers.co.kr/learn/courses/30/lessons/68645)
 - [x] golang lecture 5,6,7,8,9
 - [ ] myblog
