### ISSUE TITLE
Daily Log 2021-04-09

### ISSUE THREAD

**Issue by dongsubkim** [dongsubkim/dailylog#18]
# Daily Log 2021-04-09

## TODO

 - [x] [leetcode](https://leetcode.com/explore/challenge/card/april-leetcoding-challenge-2021/594/week-2-april-8th-april-14th/3702/)
 - [x] [project euler](https://projecteuler.net/problem=27)
 - [x] [programmers](https://programmers.co.kr/learn/courses/30/lessons/68646)
 - [x] golang lecture 10
 - [x] golang lecture 11
 - [x] golang lecture 12
 - [x] golang lecture 13
 - [ ] golang lecture 14
 - [ ] golang lecture 15
