### ISSUE TITLE
Daily Log 2021-04-10

### ISSUE THREAD

**Issue by dongsubkim** [dongsubkim/dailylog#19]
# Daily Log 2021-04-10

## TODO

 - [x] [leetcode](https://leetcode.com/explore/challenge/card/april-leetcoding-challenge-2021/594/week-2-april-8th-april-14th/3703/)
 - [x] [project euler](https://projecteuler.net/problem=28)
 - [ ] [programmers](https://programmers.co.kr/learn/courses/30/lessons/68647)
 - [ ] golang lecture 14
 - [ ] golang lecture 15
 - [ ] golang lecture 16
 - [ ] golang lecture 17
 - [ ] golang lecture 18
 - [ ] golang lecture 19
