### ISSUE TITLE
Daily Log 2021-03-26

### ISSUE THREAD

**Issue by dongsubkim** [dongsubkim/dailylog#6]
# Daily Log 2021-03-26

## TODOs

 - [x] My Blog Design
 - [x] Blog setup
 - [x] leetcode daily challenge
 - [x] project euler problem 19
